const edgeList = [
    { source: "Claudia Almerinda de Souza Oliveira", target: "Thiago Pedro Donadon Homem", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Claudia Almerinda de Souza Oliveira", target: "Felipe Rodrigues Martinez Basile", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Fernando Cesar Mendonca", target: "Fernando Luis Rossi", options: { type: "line", weight: 1, label: "", size: 2, peso: 4.0} },
    { source: "Fernando Cesar Mendonca", target: "Lincon Lopes", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Fernando Cesar Mendonca", target: "Wilian Ramalho Feitosa", options: { type: "line", weight: 1, label: "", size: 2, peso: 3.0} },
    { source: "Fernando Cesar Mendonca", target: "Robson Barbosa", options: { type: "line", weight: 1, label: "", size: 2, peso: 4.0} },
    { source: "Fernando Cesar Mendonca", target: "William Rosseti", options: { type: "line", weight: 1, label: "", size: 2, peso: 4.0} },
    { source: "Fernando Luis Rossi", target: "Wilian Ramalho Feitosa", options: { type: "line", weight: 1, label: "", size: 2, peso: 5.0} },
    { source: "Fernando Luis Rossi", target: "Robson Barbosa", options: { type: "line", weight: 1, label: "", size: 2, peso: 7.0} },
    { source: "Fernando Luis Rossi", target: "William Rosseti", options: { type: "line", weight: 1, label: "", size: 2, peso: 6.0} },
    { source: "Julio Samuel Savio Bernardo", target: "Luciana Cavalcanti Maia Santos", options: { type: "line", weight: 1, label: "", size: 2, peso: 2.0} },
    { source: "Julio Samuel Savio Bernardo", target: "Rogerio Deitali Bruno", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Patricia Cristiane Santana da Silva", target: "Luciana Cavalcanti Maia Santos", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Patricia Cristiane Santana da Silva", target: "Jair Garcia dos Santos", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Luciana Cavalcanti Maia Santos", target: "Rogerio Deitali Bruno", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Renato Marcon Pugliese", target: "Ana Carolina Vila Ramos dos Santos", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Renato Marcon Pugliese", target: "Vanessa Regina Ferreira da Silva", options: { type: "line", weight: 1, label: "", size: 2, peso: 3.0} },
    { source: "Renato Marcon Pugliese", target: "Danilo Amorim de Souza", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Renato Marcon Pugliese", target: "Tatiana Aparecida Picosque", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Lincon Lopes", target: "Wilian Ramalho Feitosa", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Luciano Henrique Trindade", target: "Wilian Ramalho Feitosa", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Silene Jucelino de Lima", target: "Wilian Ramalho Feitosa", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Silene Jucelino de Lima", target: "Robson Barbosa", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Wilian Ramalho Feitosa", target: "Robson Barbosa", options: { type: "line", weight: 1, label: "", size: 2, peso: 6.0} },
    { source: "Wilian Ramalho Feitosa", target: "William Rosseti", options: { type: "line", weight: 1, label: "", size: 2, peso: 5.0} },
    { source: "Ana Carolina Vila Ramos dos Santos", target: "Tatiana Aparecida Picosque", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Ana Carolina Vila Ramos dos Santos", target: "Vagner Luis da Silva", options: { type: "line", weight: 1, label: "", size: 2, peso: 2.0} },
    { source: "Thiago Pedro Donadon Homem", target: "Fabio Oliveira Teixeira", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Thiago Pedro Donadon Homem", target: "Felipe Rodrigues Martinez Basile", options: { type: "line", weight: 1, label: "", size: 2, peso: 2.0} },
    { source: "Thiago Pedro Donadon Homem", target: "Renato Cristiano Montanher", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Felipe Rodrigues Martinez Basile", target: "Renato Cristiano Montanher", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Felipe Rodrigues Martinez Basile", target: "Rita Roberta Marioto", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Felipe Rodrigues Martinez Basile", target: "Teresa Helena Buscato Martins", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Felipe Rodrigues Martinez Basile", target: "Luiz Roberto Albano Junior", options: { type: "line", weight: 1, label: "", size: 2, peso: 4.0} },
    { source: "Igor Calebe Zadi", target: "Renato Cristiano Montanher", options: { type: "line", weight: 1, label: "", size: 2, peso: 4.0} },
    { source: "Igor Calebe Zadi", target: "Hania Cecilia Pilan", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Igor Calebe Zadi", target: "Alex Sandro Rodrigues Ancioto", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Renato Cristiano Montanher", target: "Hania Cecilia Pilan", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Regivaldo Sousa Ferreira", target: "Rogerio Aparecido Campanari Xavier", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Regivaldo Sousa Ferreira", target: "Adriano Jose Ferruzzi", options: { type: "line", weight: 1, label: "", size: 2, peso: 2.0} },
    { source: "Ariane Macedo Melo Ferraz", target: "Irando Alves Martins Neto", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Ariane Macedo Melo Ferraz", target: "Priscila Hanako Ishy de Magalhaes", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Ariane Macedo Melo Ferraz", target: "Rita Roberta Marioto", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Ariane Macedo Melo Ferraz", target: "Junot de Oliveira Maia", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Ariane Macedo Melo Ferraz", target: "Teresa Helena Buscato Martins", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Marcelo Cizaurre Guirau", target: "Priscila Hanako Ishy de Magalhaes", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Marcelo Cizaurre Guirau", target: "Teresa Helena Buscato Martins", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} },
    { source: "Robson Barbosa", target: "William Rosseti", options: { type: "line", weight: 1, label: "", size: 2, peso: 5.0} },
    { source: "Ana Claudia Folha da Cruz", target: "Tulio Francisco da Silva Bernardo", options: { type: "line", weight: 1, label: "", size: 2, peso: 1.0} }
];

// Export the edgeList for use in other modules
export { edgeList };